command: ["uv", "run", "mcp-pablo"]

env:
  - name: "GENIE_SERIALIZATION_JOB_ID"
    value: "405956489806901"
  - name: "GENIE_RESTORE_POINTS_JOB_ID"
    value: "191614083444231"
  - name: "GENIE_RESTORE_JOB_ID"
    value: "411926808267885"
  - name: "ATLAN_API_KEY"
    valueFrom: "atlan-api-key"
  - name: "ATLAN_BASE_URL"
    value: "https://hp.atlan.com/"
  - name: "GENIE_SPACE_WAREHOUSE_ID"
    value: "09211e379d062f50"
  - name: "DATABRICKS_AUDIT_WAREHOUSE_ID"
    value: "38cb31e24512fd55"
